api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # enable_swagger: true
    # enable_swagger_ui: true
    # enable_entrypoint: true
    # formats:
    #     jsonld:
    #         mime_types: ['application/ld+json']

    #     json:
    #         mime_types: ['application/json']

    #     html:
    #         mime_types: ['text/html']

# formats:
#     json:
#         mime_types: ['application/json']
#     jsonld:
#         mime_types: ['application/ld+json']
#     html:
#         mime_types: ['text/html']
#     multipart:
#         mime_types: ['multipart/form-data']